// i18n do painel (PT · EN · ES). Reaproveita o idioma do LanguageProvider do site,
// então o seletor de idioma e o tema claro/escuro já valem aqui automaticamente.

import { useTranslation } from '../i18n/LanguageProvider'
import type { Lang } from '../i18n/translations'

const pt = {
  common: {
    loading: 'Carregando…',
    retry: 'Tentar novamente',
    cancel: 'Cancelar',
    save: 'Salvar',
    create: 'Criar',
    close: 'Fechar',
    search: 'Buscar',
    empty: 'Nada por aqui ainda.',
    upgrade: 'Fazer upgrade',
    comingSoon: 'Em breve',
    logout: 'Sair',
    copy: 'Copiar',
    copied: 'Copiado!',
    of: 'de',
  },
  topbar: { theme: 'Tema', language: 'Idioma' },
  states: {
    sessionExpired: 'Sua sessão expirou',
    sessionExpiredBody: 'Entre novamente para acessar o painel.',
    login: 'Fazer login',
    noCompany: 'Sua conta ainda não faz parte de nenhuma empresa ativa.',
    subscribe: 'Assinar um plano',
    backToSite: 'Voltar ao site',
    chooseCompany: 'Escolha a empresa',
    loadingPanel: 'Preparando seu painel…',
  },
  nav: {
    main: 'Geral',
    ops: 'Operação',
    modules: 'Módulos',
    config: 'Canais e formulários',
    admin: 'Administração',
    overview: 'Visão geral',
    cases: 'Canal de Denúncias',
    sac: 'SAC',
    nr1: 'NR-1',
    signature: 'Assinatura Digital',
    people: 'Pessoas',
    roles: 'Papéis',
    channels: 'Canais',
    formbuilder: 'Formulário',
    flow: 'Fluxo',
    billing: 'Plano',
    audit: 'Auditoria',
    settings: 'Configurações',
  },
  // SOBRESCREVE t.flow quando o canal escolhido é de SAC: a cadeia é de uma
  // DEMANDA de consumidor, não de um relato de denúncia. Só as chaves que
  // mudam — o resto vem de t.flow. NÃO declare `sev` aqui: o merge é raso e
  // substituiria o objeto inteiro.
  flowSac: {
    subtitle: 'Monte a cadeia que uma demanda de consumidor segue depois de aberta — as etapas do atendimento, quem responde e o prazo.',
    stages: 'Etapas do atendimento (configuráveis)',
    emptyStagesBody: 'Adicione as sub-etapas do atendimento — cada uma com responsável, observadores e prazo.',
    railInvestigation: 'Apuração',
    egName: 'Atendimento',
    stageNamePh: 'Ex.: Análise do pedido',
  },
  flow: {
    title: 'Construtor de Fluxo',
    subtitle: 'Monte a cadeia que um relato segue após ser enviado — as etapas da investigação, quem responde e o prazo.',
    save: 'Salvar fluxo', saved: 'Fluxo salvo.', saveFail: 'Falha ao salvar o fluxo.',
    channel: 'Canal', flowName: 'Nome do fluxo', egName: 'Investigação',
    rail: 'A cadeia completa', railReceived: 'Recebido', railTriage: 'Triagem', railInvestigation: 'Investigação', railResponded: 'Resposta', railClosed: 'Encerrado',
    stages: 'Etapas da investigação (configuráveis)',
    emptyStages: 'Nenhuma etapa ainda', emptyStagesBody: 'Adicione as sub-etapas da investigação — cada uma com responsável, observadores e prazo.',
    addStage: 'Adicionar etapa', untitled: 'Etapa sem nome',
    noChannel: 'Nenhum canal para configurar', noChannelBody: 'Crie um canal em Canais para montar o fluxo dele.',
    operator: 'Responsável (opera)', noRole: 'Sem responsável definido', sla: 'Prazo (dias)', watchers: 'Observadores (acompanham)',
    operatorPerson: 'Pessoa (opcional)', anyOfRole: 'Qualquer um do papel',
    doesWhat: 'O que essa pessoa faz', cfgDecision: 'Decisão', cfgRating: 'Nota', cfgUrgency: 'Urgência',
    mode: 'Modo do fluxo', sequential: 'Sequencial', parallel: 'Paralelo',
    sequentialHint: 'Uma etapa por vez — cada parecer libera a próxima.',
    parallelHint: 'Todos recebem ao mesmo tempo; cada um dá o seu parecer.',
    closerRole: 'Encerrador (papel)', closerPerson: 'Encerrador (pessoa)',
    requireSig: 'Exigir assinatura digital nesta etapa', requireSigHint: 'O avaliador só passa para a próxima etapa após assinar digitalmente o parecer.',
    closerRequireSig: 'Exigir assinatura digital do encerrador',
    searchPerson: 'Buscar por nome ou e-mail…', noPerson: 'Ninguém encontrado.',
    stageNamePh: 'Ex.: Apuração preliminar', conditional: 'Etapa condicional', condPrefix: 'Só executa se a gravidade for',
    sev: { low: 'Baixa', medium: 'Média', high: 'Alta', critical: 'Crítica' },
  },
  login: {
    title: 'Entrar',
    kicker: 'Acessar a Soluvia',
    email: 'E-mail',
    password: 'Senha',
    enter: 'Entrar',
    entering: 'Entrando…',
    wrong: 'E-mail ou senha inválidos.',
    noAccount: 'Ainda não tem conta?',
    subscribe: 'Assinar um plano',
    chooseCompany: 'Em qual empresa você quer entrar?',
    chooseSub: 'Sua identidade é única; o acesso muda conforme a empresa.',
  },
  overview: {
    title: 'Painel da',
    modulesTitle: 'Seus módulos',
    mod: {
      etica: { name: 'Canal de Denúncias', desc: 'Receba e trate relatos com sigilo e trilha completa.' },
      sac: { name: 'SAC · Atendimento ao Consumidor', desc: 'Demandas de consumidores com prazo de 7 dias corridos.' },
      assinatura: { name: 'Assinatura Digital', desc: 'Assine documentos e etapas com validade e evidência.' },
      nr1: { name: 'NR-1 · Riscos psicossociais', desc: 'Pesquisas e indicadores de saúde mental no trabalho.' },
      privacidade: { name: 'Privacidade (LGPD)', desc: 'Requisições de titulares e conformidade.' },
      incidentes: { name: 'Incidentes', desc: 'Registro e tratamento de incidentes.' },
    },
    welcome: 'Você está autenticado como Admin. Aqui é o seu ambiente.',
    welcomeMember: 'Bem-vindo(a) de volta. Aqui é o seu ambiente.',
    plan: 'Plano',
    users: 'Usuários',
    seatsFree: 'vaga(s) livre(s)',
    modules: 'Módulos ativos',
    openCases: 'Casos abertos',
    recent: 'Atividade recente',
    quick: 'Ações rápidas',
    quickInvite: 'Convidar pessoa',
    quickChannel: 'Criar canal',
    quickRoles: 'Gerenciar papéis',
    yourRoles: 'Seus papéis',
  },
  people: {
    title: 'Pessoas',
    subtitle: 'Convide o time e atribua papéis e escopo.',
    invite: 'Convidar pessoa',
    inviteTitle: 'Convidar pessoa',
    emailPh: 'pessoa@empresa.com',
    namePh: 'Nome (opcional)',
    role: 'Papel',
    noRole: 'Sem papel',
    send: 'Enviar convite',
    sending: 'Enviando…',
    seats: 'vagas usadas',
    remove: 'Remover',
    active: 'ativo',
    invited: 'convidado',
    suspended: 'suspenso',
    copyInvite: 'Copiar convite',
    resend: 'Reenviar', resending: 'Enviando…',
    oneEmailRule: 'Um e-mail vale por uma conta, em uma única empresa. Se a pessoa já estiver na plataforma, use outro endereço.',
    resendHint: 'Manda o convite de novo, com um código novo. O link continua o mesmo.',
    resendOk: 'Convite reenviado — um código novo foi para o e-mail.',
    resendFail: 'Não foi possível reenviar o convite.',
    inviteCreated: 'Convite criado!',
    inviteLinkHint: 'Como o e-mail ainda não está ligado, copie o link e envie manualmente. A pessoa define a senha e entra no painel dela.',
    inviteAnother: 'Convidar outra',
  },
  roles: {
    title: 'Papéis',
    subtitle: 'Papéis de sistema e os customizados da sua empresa.',
    egRole: 'Operador Ética',
    system: 'Sistema',
    custom: 'Customizado',
    permissions: 'permissões',
    new: 'Novo papel',
    builderNew: 'Criar papel',
    builderEdit: 'Editar papel',
    identity: 'Identidade',
    name: 'Nome do papel',
    color: 'Cor',
    icon: 'Ícone',
    from: 'Partir de um modelo',
    blank: 'Em branco',
    modulesH: 'Permissões por módulo',
    all: 'Todos',
    none: 'Nenhum',
    preview: 'Pré-visualização',
    activeCount: 'permissões ativas',
    save: 'Salvar papel',
    saving: 'Salvando…',
    remove: 'Remover',
    confirmRemove: 'Remover este papel? As atribuições precisam ser removidas antes.',
    readonly: 'Papel de sistema — somente leitura.',
    edit: 'Editar',
  },
  channels: {
    title: 'Canais',
    subtitle: 'Canais por módulo e o link exclusivo do Colaborador.',
    egName: 'Canal de Ética', egSlug: 'canal-de-etica',
    create: 'Criar canal',
    name: 'Nome do canal',
    slug: 'Identificador (slug)',
    module: 'Módulo',
    link: 'Link público',
    active: 'ativo',
    inactive: 'inativo',
    empty: 'Nenhum canal ainda. Crie o primeiro.',
  },
  billing: {
    title: 'Plano & cobrança',
    subtitle: 'Seu plano atual, uso e módulos contratados.',
    current: 'Plano atual',
    seats: 'Usuários',
    modules: 'Módulos',
    card: 'Cartão',
    cycle: 'Ciclo',
    monthly: 'mensal',
    yearly: 'anual',
    upgrade: 'Mudar de plano',
    status: 'Status',
    active: 'Ativa',
    canceledTag: 'Cancelada',
    accessUntil: 'Acesso até',
    renews: 'Renova em',
    currentPlan: 'Plano atual',
    doUpgrade: 'Fazer upgrade',
    doDowngrade: 'Fazer downgrade',
    switchCycle: 'Trocar ciclo',
    cancelSub: 'Cancelar assinatura',
    reactivate: 'Reativar assinatura',
    cancelTitle: 'Cancelar assinatura?',
    cancelBody: 'Sua assinatura continua ativa até o fim do período já pago. Depois disso o acesso é suspenso e não há nova cobrança. Você pode reativar quando quiser.',
    canceledBanner: 'Assinatura cancelada — você mantém acesso até o fim do período.',
    keep: 'Manter assinatura',
    changeTitle: 'Revisar mudança',
    fromTo: 'Mudança de plano',
    payNow: 'A pagar agora (proporcional)',
    creditNext: 'Crédito na próxima fatura',
    daysLeft: 'dias restantes neste ciclo',
    noCharge: 'Sem cobrança adicional agora.',
    confirmChange: 'Confirmar mudança',
    seatWarn: 'Reduza o número de usuários ativos antes de migrar para este plano.',
    dangerZone: 'Gerenciar assinatura',
    cardOnFile: 'Protegido pela Stripe',
    errCalc: 'Erro ao calcular a mudança.',
    errChange: 'Erro ao mudar de plano.',
    errCancel: 'Erro ao cancelar.',
    errReactivate: 'Erro ao reativar.',
  },
  fb: {
    title: 'Construtor de Formulário',
    subtitle: 'Monte o formulário de relato do canal — como um Google Forms.',
    noChannel: 'Nenhum canal de ética ainda',
    noChannelBody: 'Crie um canal em "Canais" para montar o formulário de denúncias.',
    save: 'Salvar', publish: 'Publicar', published: 'Formulário publicado!', saved: 'Rascunho salvo',
    errSave: 'Erro ao salvar.', errTranslate: 'Erro ao traduzir.',
    previewYes: 'Sim', previewNo: 'Não', optionEg: 'Opção',
    myForms: 'Meus formulários', untitled: 'Sem título', fieldsWord: 'campos',
    kindEtica: 'Canal de Denúncias', kindSac: 'SAC',
    identity: 'Identidade do formulário', formTitle: 'Título do formulário',
    formIntro: 'Texto de introdução (opcional)', identification: 'Identificação do denunciante',
    id: { optional: 'Opcional', required: 'Obrigatória', forbidden: 'Anônimo' },
    question: 'Pergunta', remove: 'Remover', help: 'Texto de ajuda (opcional)',
    optionsPh: 'Uma opção por linha', required: 'Obrigatório', sensitive: 'Sensível (LGPD)',
    addField: 'Adicionar pergunta', preview: 'Pré-visualização', publishedTag: 'Publicado',
    draft: 'Rascunho', answerPh: 'Resposta do denunciante', choosePh: 'Selecione',
    publicLink: 'Link público do canal', publishHint: 'Publique o formulário para o link ficar ativo.',
    types: { short_text: 'Texto curto', long_text: 'Texto longo', single_choice: 'Escolha única', multi_choice: 'Múltipla escolha', dropdown: 'Lista suspensa', date: 'Data', yes_no: 'Sim / Não', rating: 'Nota', section: 'Título de seção', info: 'Texto informativo' },
    mode: { manual: 'Manual', ai: 'Montar com IA' },
    langBuild: 'Idioma do formulário', translate: 'Traduzir p/ todos os idiomas', translating: 'Traduzindo…', translated: 'Formulário traduzido (PT · EN · ES).', langsReady: 'Idiomas prontos:',
    previewOffTitle: 'Idioma ainda não traduzido', previewOffBody: 'Este formulário ainda não tem versão neste idioma. Traduza para pré-visualizar.', previewOffCta: 'Traduzir agora',
    ai: { title: 'Assistente de formulário', intro: 'Oi! Me conta que canal você quer criar e eu monto o formulário pra você — seguindo a NR-1 e a Lei 14.457/2022, com perguntas gentis e acolhedoras. Pode pedir ajustes quando quiser. 😊', placeholder: 'Ex.: canal de assédio para uma fábrica, anônimo, com campo de setor…', send: 'Enviar', thinking: 'Montando…', apply: 'Usar este formulário', applied: 'Formulário aplicado — revise e publique.', you: 'Você', assistant: 'Assistente', agentEtica: 'Especialista em ouvidoria', agentSac: 'Especialista em SAC', newChat: 'Nova conversa', deleteChat: 'Apagar conversa', empty: 'Comece descrevendo o canal que você precisa.', starters: ['Assédio moral e sexual', 'Fraude e corrupção', 'Ética e conduta geral'], introSac: 'Oi! Me conta como funciona o atendimento da sua empresa e eu monto o formulário do SAC — seguindo o Código de Defesa do Consumidor e o Decreto 11.034/2022. Identificação obrigatória e resposta em até 7 dias corridos já entram por padrão. 😊', startersSac: ['Reclamação de produto', 'Cancelamento de serviço', 'Dúvidas e informações'], waiting: ['Entendendo o que você precisa…', 'Pensando nas melhores perguntas…', 'Aplicando a NR-1 e a Lei 14.457…', 'Deixando o tom bem acolhedor…', 'Organizando os campos…', 'Quase lá, finalizando…'] },
  },
  sig: {
    title: 'Assinatura Digital',
    subtitle: 'Envie um documento, posicione os campos e assine com validade jurídica.',
    docs: 'Documentos',
    upload: 'Enviar documento',
    uploading: 'Enviando…',
    dropHint: 'Arraste um PDF ou DOCX aqui, ou clique para escolher',
    dropTypes: 'Apenas .pdf e .docx · até 20 MB',
    invalidType: 'Formato não suportado. Envie um arquivo .pdf ou .docx.',
    tooBig: 'Arquivo muito grande (máx. 20 MB).',
    uploadFail: 'Falha ao enviar o documento.',
    emptyDocs: 'Nenhum documento ainda',
    emptyDocsBody: 'Envie o primeiro documento para começar a assinar.',
    created: 'Enviado em',
    status: { uploaded: 'Aguardando', partial: 'Parcial', signed: 'Assinado' },
    open: 'Abrir',
    back: 'Voltar aos documentos',
    prepare: 'Preparar',
    sign: 'Assinar',
    evidence: 'Comprovante',
    // Viewer
    page: 'Página',
    of: 'de',
    zoomIn: 'Ampliar',
    zoomOut: 'Reduzir',
    addFieldHint: 'Clique e arraste sobre o documento para criar um campo de assinatura.',
    fieldsCount: 'campo(s) de assinatura',
    saveFields: 'Salvar campos',
    savingFields: 'Salvando…',
    fieldsSaved: 'Campos salvos.',
    fieldsFail: 'Falha ao salvar os campos.',
    clearFields: 'Limpar campos',
    signHere: 'Assinar aqui',
    removeField: 'Remover campo',
    resizeField: 'Redimensionar campo',
    fitPage: 'Ajustar',
    fitPageHint: 'Enquadrar a página inteira',
    addFieldMode: 'Adicionar campo',
    addFieldHintTouch: 'Ligue "Adicionar campo" e toque onde a assinatura deve ficar. Com o modo desligado, você rola o documento normalmente.',
    moveFieldHint: 'Arraste um campo para movê-lo; puxe o canto para redimensionar.',
    fieldsSavedShort: 'Salvo',
    noFieldsWarn: 'Nenhum campo posicionado. A assinatura será carimbada no rodapé da última página.',
    unsavedFields: 'Os campos ainda estão sendo salvos. Volte em "Preparar", confirme que aparece "Salvo" e tente de novo — senão a assinatura vai para o rodapé da última página.',
    loadingPdf: 'Carregando documento…',
    pdfFail: 'Não foi possível renderizar este PDF.',
    docxTitle: 'Documento Word (.docx)',
    docxBody: 'O posicionamento de campos é um recurso do PDF. Documentos .docx são assinados com um bloco de assinatura anexado ao final do arquivo.',
    // Ato de assinar
    signTitle: 'Assinar documento',
    signKicker: 'Assinatura avançada',
    rubric: 'Sua rubrica',
    rubricHint: 'Desenhe sua assinatura no campo abaixo (visual).',
    rubricDraw: 'Desenhar',
    rubricType: 'Gerar do nome',
    rubricRequired: 'Adicione sua rubrica antes de assinar — desenhe ou aguarde a rubrica gerada aparecer.',
    typedName: 'Nome que vai aparecer na rubrica',
    typedPlaceholder: 'Seu nome',
    typedStyle: 'Estilo da letra',
    typedStyles: { classica: 'Clássica', fluida: 'Fluida', caneta: 'Caneta', marcador: 'Marcador' },
    typedLoading: 'Carregando estilos de letra…',
    typedHint: 'A rubrica é gerada a partir do nome digitado. O valor jurídico vem da assinatura eletrônica (chave, data/hora e trilha de auditoria), não do desenho.',
    clear: 'Limpar',
    cpf: 'CPF (opcional)',
    cpfHint: 'Reforça a identificação do signatário. Guardamos apenas mascarado.',
    remember: 'Salvar minha rubrica neste dispositivo para a próxima vez (CPF e localização nunca são salvos)',
    typeLabel: 'Tipo de assinatura', typeRubric: 'Rubrica', typeSeal: 'Assinatura digital',
    sealHint: 'Aplica uma tarja oficial de assinatura eletrônica com seu nome, CPF, data/hora e código de verificação — sem precisar desenhar.',
    geoTitle: 'Localização',
    geoHint: 'Anexar sua localização reforça a prova. Pediremos sua permissão.',
    consentTitle: 'Compartilhar sua localização?',
    consentBody: 'Com o seu consentimento, capturamos as coordenadas do seu dispositivo apenas neste momento para reforçar a evidência da assinatura. Você pode assinar sem compartilhar.',
    consentAllow: 'Permitir e capturar',
    consentDeny: 'Assinar sem localização',
    geoOn: 'Localização capturada',
    geoOff: 'Sem localização',
    geoDenied: 'Permissão negada — assinaremos sem localização.',
    geoUnavailable: 'Localização indisponível neste dispositivo.',
    geoGetting: 'Obtendo localização…',
    confirmSign: 'Assinar agora',
    signing: 'Assinando…',
    signFail: 'Falha ao assinar o documento.',
    signed: 'Documento assinado!',
    // Comprovante
    evTitle: 'Comprovante de assinatura',
    evSubtitle: 'Trilha de evidências criptográficas deste documento.',
    evFile: 'Arquivo',
    evHash: 'Hash original (SHA-256)',
    evStatus: 'Status',
    evChain: 'Cadeia de evidências',
    chainOk: 'Íntegra',
    chainBroken: 'Comprometida',
    signers: 'Signatários',
    noSigners: 'Ainda sem assinaturas.',
    signerName: 'Signatário',
    algo: 'Algoritmo',
    level: 'Nível',
    signedAt: 'Assinado em',
    geo: 'Localização',
    notConsented: 'não consentida',
    ip: 'IP',
    userAgent: 'Dispositivo',
    cpfMasked: 'CPF',
    cpfStatus: 'Situação do CPF',
    evHashLabel: 'Hash da evidência',
    prevHash: 'Hash anterior',
    verifyToken: 'Token de verificação',
    downloadSigned: 'Baixar arquivo assinado',
    downloading: 'Baixando…',
    downloadFail: 'Falha ao baixar o arquivo.',
    copyVerify: 'Copiar link de verificação',
    verifyLink: 'Link de verificação',
    evLoadFail: 'Falha ao carregar o comprovante.',
  },
  audit: {
    title: 'Auditoria',
    subtitle: 'Trilha imutável de tudo que acontece na empresa — quem fez o quê, e quando.',
    empty: 'Sem registros ainda.', noMatch: 'Nenhum evento com esses filtros.',
    filters: 'Filtros', from: 'De', to: 'Até', action: 'Ação', person: 'Pessoa',
    all: 'Todas as ações', allPeople: 'Todas as pessoas', search: 'Buscar…', clear: 'Limpar filtros',
    events: 'eventos', system: 'Sistema', today: 'Hoje', yesterday: 'Ontem',
    export: 'Exportar PDF', exporting: 'Gerando…', exportOk: 'PDF gerado.', exportFail: 'Falha ao gerar o PDF.',
    integrityOk: 'Trilha íntegra', integrityBroken: 'Integridade comprometida',
    integrityHint: 'Cada evento encadeia o anterior por hash (SHA-256). A cadeia foi recalculada e está intacta — nenhum registro foi alterado ou removido.',
    integrityBrokenHint: 'A cadeia de hash não confere: algum registro foi alterado ou removido. Contate o suporte.',
    exportTitle: 'Trilha de auditoria', colWhen: 'Quando', colWho: 'Quem', colWhat: 'O que aconteceu', colDetail: 'Detalhe',
    cat: { case: 'Casos', signature: 'Assinatura', flow: 'Fluxo', channel: 'Canais e formulários', role: 'Papéis e pessoas', billing: 'Plano', account: 'Conta e LGPD', tenant: 'Empresa', other: 'Outros' },
    res: { sig_document: 'documento', channel: 'canal', case: 'caso', flow: 'fluxo', role: 'papel', user: 'usuário', tenant: 'empresa', data_request: 'solicitação LGPD', membership: 'membro' },
    act: {
      'signature.signed': 'assinou um documento', 'flow.saved': 'salvou o fluxo de um canal',
      'case.created': 'abriu um caso', 'case.advanced': 'avançou a etapa de um caso', 'case.closed': 'encerrou um caso',
      'case.event.message': 'respondeu ao denunciante', 'case.event.note': 'adicionou uma nota interna',
      'case.event.status_change': 'mudou o status de um caso', 'case.event.stage_change': 'mudou a etapa de um caso',
      'case.event.created': 'registrou um evento no caso', 'case.event.closed': 'encerrou um caso',
      'channel.created': 'criou um canal', 'channel.updated': 'atualizou um canal',
      'channel.form_saved': 'salvou o formulário de um canal', 'channel.form_translated': 'traduziu o formulário de um canal',
      'channel.form_published': 'publicou o formulário de um canal',
      'role.created': 'criou um papel', 'role.updated': 'editou um papel', 'role.deleted': 'removeu um papel',
      'membership.invited': 'convidou uma pessoa', 'membership.accepted': 'aceitou um convite',
      'membership.status_changed': 'alterou o status de um membro', 'membership.removed': 'removeu um membro',
      'membership.role_assigned': 'atribuiu um papel a um membro', 'membership.role_removed': 'removeu um papel de um membro',
      'billing.subscribed': 'assinou um plano', 'billing.plan_changed': 'mudou de plano',
      'billing.canceled': 'cancelou a assinatura', 'billing.reactivated': 'reativou a assinatura',
      'billing.webhook': 'recebeu um evento de pagamento',
      'account.deleted': 'excluiu a própria conta', 'account.profile_updated': 'atualizou o perfil',
      'account.password_changed': 'alterou a senha', 'lgpd.data_exported': 'exportou seus dados (LGPD)',
      'lgpd.request': 'fez uma solicitação LGPD', 'tenant.self_signup': 'cadastrou a empresa',
      'tenant.provisioned': 'provisionou a empresa', 'tenant.profile_updated': 'atualizou os dados da empresa',
    },
  },
  // SOBRESCREVE t.cases quando o canal é de SAC: aqui quem escreve é CONSUMIDOR,
  // não denunciante. Só as chaves que mudam — o resto vem de t.cases.
  sac: {
    title: 'SAC — Atendimento ao Consumidor',
    subtitle: 'Demandas de consumidores, com prazo de resposta de 7 dias corridos (Decreto 11.034/2022).',
    createChannel: 'Criar um canal de SAC',
    due: { late: 'Atrasado', today: 'Vence hoje', inDays: 'Faltam {n} d' },
    empty: 'Nenhuma demanda no seu escopo ainda.',
    noActive: 'Nenhuma demanda em aberto.', noFinished: 'Nenhuma demanda finalizada ainda.',
    active: 'Em aberto', finished: 'Finalizadas',
    searchPh: 'Buscar por título ou protocolo…',
    relato: 'Demanda', closeL: 'Encerrar demanda',
    respondL: 'Responder ao consumidor', showOutcome: 'Mostrar o desfecho ao consumidor',
    rsigTitle: 'Assinatura do consumidor',
    replyPh: 'Mensagem visível ao consumidor (pelo protocolo)…',
    notePh: 'Nota interna (nunca vai ao consumidor)…',
    closePh: 'Desfecho da demanda…',
    failOpen: 'Falha ao abrir a demanda.',
    notFoundProtocol: 'Demanda não encontrada neste módulo.',
    ev: { note: 'nota interna', opening: 'abertura', closing: 'encerramento', stage: 'etapa',
          fromReporter: 'do consumidor', toReporter: 'ao consumidor' },
  },
  cases: {
    title: 'Casos',
    subtitle: 'Relatos no seu escopo de acesso.',
    protocol: 'Protocolo',
    status: 'Status',
    severity: 'Gravidade',
    opened: 'Aberto em',
    empty: 'Nenhum caso no seu escopo ainda.',
    active: 'Ativas', finished: 'Finalizadas',
    noActive: 'Nenhuma denúncia ativa no momento.', noFinished: 'Nenhuma finalizada ainda.',
    searchPh: 'Buscar por título ou protocolo…', noMatch: 'Nada encontrado para a busca.',
    sev: { low: 'Baixa', medium: 'Média', high: 'Alta', critical: 'Crítica' },
    stat: { received: 'Recebido', triage: 'Triagem', investigation: 'Investigação', responded: 'Respondido', closed: 'Encerrado' },
    anon: 'Anônimo', identified: 'Identificado',
    rsigTitle: 'Assinatura do denunciante', rsigSignedAt: 'Assinado em', rsigCpf: 'CPF', rsigGeo: 'Localização', rsigNoGeo: 'não informada',
    relato: 'Relato', timeline: 'Linha do tempo', triageL: 'Triagem', respondL: 'Responder ao denunciante', noteL: 'Anotação interna', closeL: 'Encerrar caso',
    applySev: 'Aplicar gravidade', advance: 'Avançar etapa →', sendReply: 'Enviar resposta', addNote: 'Adicionar nota', showOutcome: 'Mostrar o desfecho ao denunciante',
    signStageL: 'Assinatura da etapa', signStage: 'Assinar esta etapa', stageSigned: 'Etapa assinada e encadeada à trilha do caso · link de verificação copiado',
    replyPh: 'Mensagem visível ao denunciante (pelo protocolo)…', notePh: 'Nota confidencial (nunca vai ao denunciante)…', closePh: 'Parecer / desfecho do caso…',
    ev: { note: 'nota interna', opening: 'abertura', closing: 'encerramento', stage: 'etapa', fromReporter: 'do denunciante', toReporter: 'ao denunciante' },
    notFoundProtocol: 'Caso não encontrado neste módulo.',
    fail: 'Falha na ação.', failOpen: 'Falha ao abrir o caso.', loading: 'Carregando…', downloadPdf: 'Baixar PDF', createChannel: 'Criar um canal de denúncia',
    inv: {
      title: 'Investigação', release: 'Liberar fluxo',
      releaseHint: 'Gera as fichas de parecer e inicia a investigação seguindo o fluxo do canal.',
      anyOf: 'Qualquer um de', closer: 'Encerramento', give: 'Dar meu parecer', decision: 'Decisão',
      rating: 'Nota', urgency: 'Urgência', pareceerPh: 'Escreva seu parecer…', submit: 'Enviar parecer', sent: 'Parecer enviado.',
      signed: 'Assinado ✓', verifyLink: 'Verificar', submitSign: 'Assinar e enviar',
      sigRequired: 'Esta etapa exige sua assinatura digital. Ao enviar, abriremos a assinatura (rubrica + localização) e o caso segue para o próximo.',
      flowManaged: 'O andamento (avançar e encerrar) é controlado pelo fluxo de pareceres acima.',
      needRubric: 'Desenhe sua rubrica para assinar.', signAndSend: 'Assinar e enviar parecer',
      status: { pending: 'Aguardando', active: 'Sua vez', submitted: 'Concluído', skipped: 'Pulado' },
      dec: { agree: 'De acordo', more_info: 'Mais apuração', dismiss: 'Arquivar' },
      urg: { low: 'Baixa', medium: 'Média', high: 'Alta' },
    },
  },
  nr1: {
    title: 'NR-1 Psicossocial',
    subtitle: 'Resultados agregados por eixo temático.',
    locked: 'O módulo NR-1 não está no seu plano.',
    axis: 'Eixo',
    average: 'Média',
    responses: 'Respostas',
    cycle: 'Ciclo', egCycle: '2026-T2',
  },
  locked: {
    title: 'Disponível em planos superiores',
    body: 'Este módulo não está no seu plano atual.',
  },
  settings: {
    title: 'Configurações',
    subtitle: 'Preferências, conta e seus dados (LGPD).',
    appearance: 'Aparência',
    theme: 'Tema',
    light: 'Claro',
    dark: 'Escuro',
    system: 'Sistema',
    fontSize: 'Tamanho da fonte',
    sizeS: 'Pequena',
    sizeM: 'Média',
    sizeL: 'Grande',
    sizeXL: 'Máxima',
    language: 'Idioma',
    langAuto: 'Automático',
    langHint: 'Definimos esse idioma sempre que você abrir o site neste navegador.',
    account: 'Conta',
    name: 'Nome',
    save: 'Salvar',
    changePassword: 'Alterar senha',
    currentPassword: 'Senha atual',
    newPassword: 'Nova senha',
    privacy: 'Privacidade',
    privacyIntro: 'Baixe, ajuste ou apague seus dados quando quiser — você está no controle.',
    exportData: 'Seus dados',
    exportHint: 'Baixe tudo o que guardamos sobre você.',
    aiTitle: 'Uso de IA', aiUnlimited: 'Tokens de IA ilimitados neste plano.', aiTokens: 'tokens',
    aiRemaining: 'Restam', aiYou: 'Seu consumo', aiCompany: 'Cota da empresa', aiNoPersonalLimit: 'sem limite pessoal',
    aiTeamTitle: 'Créditos de IA da equipe', aiTeamHint: 'Libere mais tokens para cada pessoa conforme a necessidade.',
    aiAddCredit: 'Adicionar', aiCreditsPh: '+ tokens',
    download: 'Baixar',
    comms: 'Comunicações por e-mail',
    commsHint: 'Receber novidades e avisos do produto.',
    on: 'Ativado',
    off: 'Desativado',
    dangerZone: 'Excluir conta',
    dangerHint: 'Remove sua conta e seus dados pessoais. Não dá para desfazer.',
    deleteAccount: 'Excluir minha conta',
    deleteConfirmTitle: 'Excluir sua conta?',
    deleteConfirmBody: 'Isso remove permanentemente sua conta, seus acessos e seus dados pessoais. Esta ação é irreversível.',
    deleteYes: 'Sim, excluir tudo',
    accountDeleted: 'Sua conta foi excluída.',
    legal: 'Documentos',
    terms: 'Termos de Uso',
    privacyPolicy: 'Política de Privacidade',
    saved: 'Salvo!',
  },
  onb: {
    welcome: 'Bem-vindo à Soluvia',
    tagline: 'Confiança digital para ética e privacidade.',
    personalize: 'Vamos deixar a experiência do seu jeito — leva 10 segundos.',
    start: 'Personalizar',
    skip: 'Pular',
    back: 'Voltar',
    next: 'Continuar',
    themeQ: 'Claro ou escuro?',
    langQ: 'Qual idioma?',
    fontQ: 'Tamanho do texto',
    doneTitle: 'Tudo pronto! ✨',
    doneBody: 'Você pode mudar tudo isso quando quiser em Configurações.',
    enter: 'Entrar',
  },
  modules: {
    etica: 'Ética & Denúncias',
    sac: 'SAC · Atendimento ao Consumidor',
    privacidade: 'Privacidade (LGPD)',
    incidentes: 'Incidentes',
    nr1: 'NR-1 Psicossocial',
    assinatura: 'Assinatura Digital',
    admin: 'Administração',
  },
}

type AppStrings = typeof pt

const en: AppStrings = {
  common: {
    loading: 'Loading…',
    retry: 'Try again',
    cancel: 'Cancel',
    save: 'Save',
    create: 'Create',
    close: 'Close',
    search: 'Search',
    empty: 'Nothing here yet.',
    upgrade: 'Upgrade',
    comingSoon: 'Coming soon',
    logout: 'Log out',
    copy: 'Copy',
    copied: 'Copied!',
    of: 'of',
  },
  topbar: { theme: 'Theme', language: 'Language' },
  states: {
    sessionExpired: 'Your session expired',
    sessionExpiredBody: 'Sign in again to access the panel.',
    login: 'Sign in',
    noCompany: 'Your account is not part of any active company yet.',
    subscribe: 'Choose a plan',
    backToSite: 'Back to site',
    chooseCompany: 'Choose a company',
    loadingPanel: 'Preparing your panel…',
  },
  nav: {
    main: 'General',
    ops: 'Operations',
    modules: 'Modules',
    config: 'Channels & forms',
    admin: 'Administration',
    overview: 'Overview',
    cases: 'Whistleblowing Channel',
    sac: 'Consumer Service',
    nr1: 'NR-1',
    signature: 'Digital Signature',
    people: 'People',
    roles: 'Roles',
    channels: 'Channels',
    formbuilder: 'Form',
    flow: 'Flow',
    billing: 'Plan',
    audit: 'Audit',
    settings: 'Settings',
  },
  flowSac: {
    subtitle: 'Design the chain a consumer demand follows after it is opened — the service stages, who handles them and the deadline.',
    stages: 'Service stages (configurable)',
    emptyStagesBody: 'Add the service sub-stages — each with an owner, watchers and a deadline.',
    railInvestigation: 'Handling',
    egName: 'Service',
    stageNamePh: 'e.g. Request analysis',
  },
  flow: {
    title: 'Flow Builder',
    subtitle: 'Design the chain a report follows after submission — the investigation stages, who handles them and the deadline.',
    save: 'Save flow', saved: 'Flow saved.', saveFail: 'Failed to save the flow.',
    channel: 'Channel', flowName: 'Flow name', egName: 'Investigation',
    rail: 'The full chain', railReceived: 'Received', railTriage: 'Triage', railInvestigation: 'Investigation', railResponded: 'Response', railClosed: 'Closed',
    stages: 'Investigation stages (configurable)',
    emptyStages: 'No stages yet', emptyStagesBody: 'Add the investigation sub-stages — each with an owner, watchers and a deadline.',
    addStage: 'Add stage', untitled: 'Untitled stage',
    noChannel: 'No channel to configure', noChannelBody: 'Create a channel under Channels to build its flow.',
    operator: 'Owner (handles it)', noRole: 'No owner set', sla: 'Deadline (days)', watchers: 'Watchers (follow along)',
    operatorPerson: 'Person (optional)', anyOfRole: 'Anyone with the role',
    doesWhat: 'What this person does', cfgDecision: 'Decision', cfgRating: 'Rating', cfgUrgency: 'Urgency',
    mode: 'Flow mode', sequential: 'Sequential', parallel: 'Parallel',
    sequentialHint: 'One stage at a time — each review unlocks the next.',
    parallelHint: 'Everyone gets it at once; each gives their review.',
    closerRole: 'Closer (role)', closerPerson: 'Closer (person)',
    requireSig: 'Require a digital signature at this stage', requireSigHint: 'The reviewer only moves to the next stage after digitally signing their review.',
    closerRequireSig: 'Require the closer’s digital signature',
    searchPerson: 'Search by name or email…', noPerson: 'No one found.',
    stageNamePh: 'e.g. Preliminary review', conditional: 'Conditional stage', condPrefix: 'Only runs if severity is',
    sev: { low: 'Low', medium: 'Medium', high: 'High', critical: 'Critical' },
  },
  login: {
    title: 'Sign in',
    kicker: 'Access Soluvia',
    email: 'Email',
    password: 'Password',
    enter: 'Sign in',
    entering: 'Signing in…',
    wrong: 'Invalid email or password.',
    noAccount: "Don't have an account?",
    subscribe: 'Choose a plan',
    chooseCompany: 'Which company do you want to enter?',
    chooseSub: 'Your identity is unique; access changes per company.',
  },
  overview: {
    title: 'Panel —',
    modulesTitle: 'Your modules',
    mod: {
      etica: { name: 'Whistleblowing Channel', desc: 'Receive and handle reports confidentially, with a full trail.' },
      sac: { name: 'Consumer Service', desc: 'Consumer requests answered within 7 calendar days.' },
      assinatura: { name: 'Digital Signature', desc: 'Sign documents and case stages with legal validity and evidence.' },
      nr1: { name: 'NR-1 · Psychosocial risk', desc: 'Surveys and indicators for mental health at work.' },
      privacidade: { name: 'Privacy (LGPD)', desc: 'Data-subject requests and compliance.' },
      incidentes: { name: 'Incidents', desc: 'Log and handle incidents.' },
    },
    welcome: 'You are signed in as Admin. This is your workspace.',
    welcomeMember: 'Welcome back. This is your workspace.',
    plan: 'Plan',
    users: 'Users',
    seatsFree: 'seat(s) free',
    modules: 'Active modules',
    openCases: 'Open cases',
    recent: 'Recent activity',
    quick: 'Quick actions',
    quickInvite: 'Invite person',
    quickChannel: 'Create channel',
    quickRoles: 'Manage roles',
    yourRoles: 'Your roles',
  },
  people: {
    title: 'People',
    subtitle: 'Invite your team and assign roles and scope.',
    invite: 'Invite person',
    inviteTitle: 'Invite person',
    emailPh: 'person@company.com',
    namePh: 'Name (optional)',
    role: 'Role',
    noRole: 'No role',
    send: 'Send invite',
    sending: 'Sending…',
    seats: 'seats used',
    remove: 'Remove',
    active: 'active',
    invited: 'invited',
    suspended: 'suspended',
    copyInvite: 'Copy invite',
    resend: 'Resend', resending: 'Sending…',
    oneEmailRule: 'One email is worth one account, in a single company. If the person is already on the platform, use a different address.',
    resendHint: 'Sends the invite again with a new code. The link stays the same.',
    resendOk: 'Invite resent — a new code is on its way.',
    resendFail: 'Could not resend the invite.',
    inviteCreated: 'Invite created!',
    inviteLinkHint: 'Email is not wired yet, so copy the link and send it manually. The person sets a password and enters their panel.',
    inviteAnother: 'Invite another',
  },
  roles: {
    title: 'Roles',
    subtitle: 'System roles and your company custom ones.',
    egRole: 'Ethics Officer',
    system: 'System',
    custom: 'Custom',
    permissions: 'permissions',
    new: 'New role',
    builderNew: 'Create role',
    builderEdit: 'Edit role',
    identity: 'Identity',
    name: 'Role name',
    color: 'Color',
    icon: 'Icon',
    from: 'Start from a template',
    blank: 'Blank',
    modulesH: 'Permissions by module',
    all: 'All',
    none: 'None',
    preview: 'Preview',
    activeCount: 'active permissions',
    save: 'Save role',
    saving: 'Saving…',
    remove: 'Remove',
    confirmRemove: 'Remove this role? Assignments must be removed first.',
    readonly: 'System role — read only.',
    edit: 'Edit',
  },
  channels: {
    title: 'Channels',
    subtitle: 'Channels per module and the Reporter exclusive link.',
    egName: 'Ethics Channel', egSlug: 'ethics-channel',
    create: 'Create channel',
    name: 'Channel name',
    slug: 'Identifier (slug)',
    module: 'Module',
    link: 'Public link',
    active: 'active',
    inactive: 'inactive',
    empty: 'No channels yet. Create the first one.',
  },
  billing: {
    title: 'Plan & billing',
    subtitle: 'Your current plan, usage and contracted modules.',
    current: 'Current plan',
    seats: 'Users',
    modules: 'Modules',
    card: 'Card',
    cycle: 'Cycle',
    monthly: 'monthly',
    yearly: 'yearly',
    upgrade: 'Change plan',
    status: 'Status',
    active: 'Active',
    canceledTag: 'Canceled',
    accessUntil: 'Access until',
    renews: 'Renews on',
    currentPlan: 'Current plan',
    doUpgrade: 'Upgrade',
    doDowngrade: 'Downgrade',
    switchCycle: 'Switch cycle',
    cancelSub: 'Cancel subscription',
    reactivate: 'Reactivate subscription',
    cancelTitle: 'Cancel subscription?',
    cancelBody: 'Your subscription stays active until the end of the period you already paid for. After that, access is suspended and there is no new charge. You can reactivate anytime.',
    canceledBanner: 'Subscription canceled — you keep access until the end of the period.',
    keep: 'Keep subscription',
    changeTitle: 'Review change',
    fromTo: 'Plan change',
    payNow: 'Due now (prorated)',
    creditNext: 'Credit on next invoice',
    daysLeft: 'days left in this cycle',
    noCharge: 'No additional charge now.',
    confirmChange: 'Confirm change',
    seatWarn: 'Reduce the number of active users before moving to this plan.',
    dangerZone: 'Manage subscription',
    cardOnFile: 'Secured by Stripe',
    errCalc: 'Error calculating the change.',
    errChange: 'Error changing plan.',
    errCancel: 'Error canceling.',
    errReactivate: 'Error reactivating.',
  },
  fb: {
    title: 'Form Builder',
    subtitle: 'Build the channel report form — like a Google Form.',
    noChannel: 'No ethics channel yet',
    noChannelBody: 'Create a channel under "Channels" to build the report form.',
    save: 'Save', publish: 'Publish', published: 'Form published!', saved: 'Draft saved',
    errSave: 'Error saving.', errTranslate: 'Error translating.',
    previewYes: 'Yes', previewNo: 'No', optionEg: 'Option',
    myForms: 'My forms', untitled: 'Untitled', fieldsWord: 'fields',
    kindEtica: 'Whistleblowing', kindSac: 'Consumer service',
    identity: 'Form identity', formTitle: 'Form title',
    formIntro: 'Intro text (optional)', identification: 'Reporter identification',
    id: { optional: 'Optional', required: 'Required', forbidden: 'Anonymous' },
    question: 'Question', remove: 'Remove', help: 'Help text (optional)',
    optionsPh: 'One option per line', required: 'Required', sensitive: 'Sensitive (privacy)',
    addField: 'Add question', preview: 'Preview', publishedTag: 'Published',
    draft: 'Draft', answerPh: 'Reporter answer', choosePh: 'Select',
    publicLink: 'Channel public link', publishHint: 'Publish the form to activate the link.',
    types: { short_text: 'Short text', long_text: 'Long text', single_choice: 'Single choice', multi_choice: 'Multiple choice', dropdown: 'Dropdown', date: 'Date', yes_no: 'Yes / No', rating: 'Rating', section: 'Section title', info: 'Info text' },
    mode: { manual: 'Manual', ai: 'Build with AI' },
    langBuild: 'Form language', translate: 'Translate to all languages', translating: 'Translating…', translated: 'Form translated (PT · EN · ES).', langsReady: 'Ready in:',
    previewOffTitle: 'Language not translated yet', previewOffBody: 'This form has no version in this language yet. Translate to preview.', previewOffCta: 'Translate now',
    ai: { title: 'Form assistant', intro: 'Hi! Tell me what channel you want to create and I\'ll build the form for you — following NR-1 and Law 14.457/2022, with gentle, caring questions. Ask for changes anytime. 😊', placeholder: 'E.g.: harassment channel for a factory, anonymous, with a department field…', send: 'Send', thinking: 'Building…', apply: 'Use this form', applied: 'Form applied — review and publish.', you: 'You', assistant: 'Assistant', agentEtica: 'Whistleblowing specialist', agentSac: 'Consumer-service specialist', newChat: 'New chat', deleteChat: 'Delete chat', empty: 'Start by describing the channel you need.', starters: ['Moral & sexual harassment', 'Fraud & corruption', 'General ethics & conduct'], introSac: 'Hi! Tell me how your company handles customers and I will build the consumer-service form — following the Brazilian Consumer Code and Decree 11,034/2022. Mandatory identification and a 7-calendar-day reply deadline come built in. 😊', startersSac: ['Product complaint', 'Service cancellation', 'Questions & information'], waiting: ['Understanding what you need…', 'Thinking of the best questions…', 'Applying NR-1 and Law 14.457…', 'Keeping the tone caring…', 'Organizing the fields…', 'Almost there, wrapping up…'] },
  },
  sig: {
    title: 'Digital Signature',
    subtitle: 'Upload a document, place the fields and sign with legal validity.',
    docs: 'Documents',
    upload: 'Upload document',
    uploading: 'Uploading…',
    dropHint: 'Drag a PDF or DOCX here, or click to choose',
    dropTypes: 'Only .pdf and .docx · up to 20 MB',
    invalidType: 'Unsupported format. Please upload a .pdf or .docx file.',
    tooBig: 'File too large (max 20 MB).',
    uploadFail: 'Failed to upload the document.',
    emptyDocs: 'No documents yet',
    emptyDocsBody: 'Upload your first document to start signing.',
    created: 'Uploaded on',
    status: { uploaded: 'Awaiting', partial: 'Partial', signed: 'Signed' },
    open: 'Open',
    back: 'Back to documents',
    prepare: 'Prepare',
    sign: 'Sign',
    evidence: 'Receipt',
    // Viewer
    page: 'Page',
    of: 'of',
    zoomIn: 'Zoom in',
    zoomOut: 'Zoom out',
    addFieldHint: 'Click and drag over the document to create a signature field.',
    fieldsCount: 'signature field(s)',
    saveFields: 'Save fields',
    savingFields: 'Saving…',
    fieldsSaved: 'Fields saved.',
    fieldsFail: 'Failed to save the fields.',
    clearFields: 'Clear fields',
    signHere: 'Sign here',
    removeField: 'Remove field',
    resizeField: 'Resize field',
    fitPage: 'Fit',
    fitPageHint: 'Fit the whole page',
    addFieldMode: 'Add field',
    addFieldHintTouch: 'Turn on "Add field" and tap where the signature should go. With it off, you scroll the document normally.',
    moveFieldHint: 'Drag a field to move it; pull the corner to resize.',
    fieldsSavedShort: 'Saved',
    noFieldsWarn: 'No field placed. The signature will be stamped at the bottom of the last page.',
    unsavedFields: 'Fields are still being saved. Go back to "Prepare", make sure it says "Saved" and try again — otherwise the signature goes to the bottom of the last page.',
    loadingPdf: 'Loading document…',
    pdfFail: 'Could not render this PDF.',
    docxTitle: 'Word document (.docx)',
    docxBody: 'Field positioning is a PDF feature. .docx documents are signed with a signature block appended to the end of the file.',
    // Signing act
    signTitle: 'Sign document',
    signKicker: 'Advanced signature',
    rubric: 'Your signature',
    rubricHint: 'Draw your signature in the box below (visual).',
    rubricDraw: 'Draw',
    rubricType: 'Generate from name',
    rubricRequired: 'Add your signature before signing — draw it or wait for the generated one to appear.',
    typedName: 'Name to show on the signature',
    typedPlaceholder: 'Your name',
    typedStyle: 'Handwriting style',
    typedStyles: { classica: 'Classic', fluida: 'Flowing', caneta: 'Pen', marcador: 'Marker' },
    typedLoading: 'Loading handwriting styles…',
    typedHint: 'The signature image is generated from the name you type. Legal weight comes from the electronic signature (key, timestamp and audit trail), not from the drawing.',
    clear: 'Clear',
    cpf: 'CPF (optional)',
    cpfHint: 'Reinforces the signer identity. We store it masked only.',
    remember: 'Save my signature on this device for next time (ID number and location are never saved)',
    typeLabel: 'Signature type', typeRubric: 'Handwritten', typeSeal: 'Digital seal',
    sealHint: 'Applies an official electronic-signature seal with your name, CPF, date/time and verification code — no drawing needed.',
    geoTitle: 'Location',
    geoHint: 'Attaching your location strengthens the proof. We will ask for your permission.',
    consentTitle: 'Share your location?',
    consentBody: 'With your consent, we capture your device coordinates only at this moment to strengthen the signature evidence. You can sign without sharing.',
    consentAllow: 'Allow and capture',
    consentDeny: 'Sign without location',
    geoOn: 'Location captured',
    geoOff: 'No location',
    geoDenied: 'Permission denied — we will sign without location.',
    geoUnavailable: 'Location unavailable on this device.',
    geoGetting: 'Getting location…',
    confirmSign: 'Sign now',
    signing: 'Signing…',
    signFail: 'Failed to sign the document.',
    signed: 'Document signed!',
    // Receipt
    evTitle: 'Signature receipt',
    evSubtitle: 'Cryptographic evidence trail for this document.',
    evFile: 'File',
    evHash: 'Original hash (SHA-256)',
    evStatus: 'Status',
    evChain: 'Evidence chain',
    chainOk: 'Intact',
    chainBroken: 'Broken',
    signers: 'Signers',
    noSigners: 'No signatures yet.',
    signerName: 'Signer',
    algo: 'Algorithm',
    level: 'Level',
    signedAt: 'Signed at',
    geo: 'Location',
    notConsented: 'not consented',
    ip: 'IP',
    userAgent: 'Device',
    cpfMasked: 'CPF',
    cpfStatus: 'CPF status',
    evHashLabel: 'Evidence hash',
    prevHash: 'Previous hash',
    verifyToken: 'Verification token',
    downloadSigned: 'Download signed file',
    downloading: 'Downloading…',
    downloadFail: 'Failed to download the file.',
    copyVerify: 'Copy verify link',
    verifyLink: 'Verify link',
    evLoadFail: 'Failed to load the receipt.',
  },
  audit: {
    title: 'Audit',
    subtitle: 'Immutable trail of everything in the company — who did what, and when.',
    empty: 'No records yet.', noMatch: 'No events match these filters.',
    filters: 'Filters', from: 'From', to: 'To', action: 'Action', person: 'Person',
    all: 'All actions', allPeople: 'All people', search: 'Search…', clear: 'Clear filters',
    events: 'events', system: 'System', today: 'Today', yesterday: 'Yesterday',
    export: 'Export PDF', exporting: 'Generating…', exportOk: 'PDF generated.', exportFail: 'Failed to generate the PDF.',
    integrityOk: 'Trail intact', integrityBroken: 'Integrity compromised',
    integrityHint: 'Each event chains the previous one by hash (SHA-256). The chain was recomputed and is intact — no record was altered or removed.',
    integrityBrokenHint: 'The hash chain does not match: a record was altered or removed. Contact support.',
    exportTitle: 'Audit trail', colWhen: 'When', colWho: 'Who', colWhat: 'What happened', colDetail: 'Detail',
    cat: { case: 'Cases', signature: 'Signature', flow: 'Flow', channel: 'Channels & forms', role: 'Roles & people', billing: 'Plan', account: 'Account & privacy', tenant: 'Company', other: 'Other' },
    res: { sig_document: 'document', channel: 'channel', case: 'case', flow: 'flow', role: 'role', user: 'user', tenant: 'company', data_request: 'privacy request', membership: 'member' },
    act: {
      'signature.signed': 'signed a document', 'flow.saved': "saved a channel's flow",
      'case.created': 'opened a case', 'case.advanced': 'advanced a case stage', 'case.closed': 'closed a case',
      'case.event.message': 'replied to the reporter', 'case.event.note': 'added an internal note',
      'case.event.status_change': 'changed a case status', 'case.event.stage_change': 'changed a case stage',
      'case.event.created': 'logged a case event', 'case.event.closed': 'closed a case',
      'channel.created': 'created a channel', 'channel.updated': 'updated a channel',
      'channel.form_saved': "saved a channel's form", 'channel.form_translated': "translated a channel's form",
      'channel.form_published': "published a channel's form",
      'role.created': 'created a role', 'role.updated': 'edited a role', 'role.deleted': 'removed a role',
      'membership.invited': 'invited a person', 'membership.accepted': 'accepted an invite',
      'membership.status_changed': "changed a member's status", 'membership.removed': 'removed a member',
      'membership.role_assigned': 'assigned a role to a member', 'membership.role_removed': 'removed a role from a member',
      'billing.subscribed': 'subscribed to a plan', 'billing.plan_changed': 'changed plan',
      'billing.canceled': 'canceled the subscription', 'billing.reactivated': 'reactivated the subscription',
      'billing.webhook': 'received a payment event',
      'account.deleted': 'deleted their account', 'account.profile_updated': 'updated their profile',
      'account.password_changed': 'changed their password', 'lgpd.data_exported': 'exported their data (privacy)',
      'lgpd.request': 'made a privacy request', 'tenant.self_signup': 'signed up the company',
      'tenant.provisioned': 'provisioned the company', 'tenant.profile_updated': "updated the company's details",
    },
  },
  sac: {
    title: 'Consumer Service',
    subtitle: 'Consumer requests, answered within 7 calendar days (Brazilian Decree 11,034/2022).',
    createChannel: 'Create a consumer service channel',
    due: { late: 'Overdue', today: 'Due today', inDays: '{n} d left' },
    empty: 'No requests in your scope yet.',
    noActive: 'No open requests.', noFinished: 'No closed requests yet.',
    active: 'Open', finished: 'Closed',
    searchPh: 'Search by title or protocol…',
    relato: 'Request', closeL: 'Close request',
    respondL: 'Reply to the consumer', showOutcome: 'Show the outcome to the consumer',
    rsigTitle: "Consumer's signature",
    replyPh: 'Message visible to the consumer (via protocol)…',
    notePh: 'Internal note (never sent to the consumer)…',
    closePh: 'Request outcome…',
    failOpen: 'Could not open the request.',
    notFoundProtocol: 'Request not found in this module.',
    ev: { note: 'internal note', opening: 'opening', closing: 'closing', stage: 'stage',
          fromReporter: 'from the consumer', toReporter: 'to the consumer' },
  },
  cases: {
    title: 'Cases',
    subtitle: 'Reports within your access scope.',
    protocol: 'Protocol',
    status: 'Status',
    severity: 'Severity',
    opened: 'Opened',
    empty: 'No cases in your scope yet.',
    active: 'Active', finished: 'Closed',
    noActive: 'No active reports right now.', noFinished: 'None closed yet.',
    searchPh: 'Search by title or protocol…', noMatch: 'Nothing matched your search.',
    sev: { low: 'Low', medium: 'Medium', high: 'High', critical: 'Critical' },
    stat: { received: 'Received', triage: 'Triage', investigation: 'Investigation', responded: 'Answered', closed: 'Closed' },
    anon: 'Anonymous', identified: 'Identified',
    rsigTitle: 'Reporter signature', rsigSignedAt: 'Signed on', rsigCpf: 'CPF', rsigGeo: 'Location', rsigNoGeo: 'not provided',
    relato: 'Report', timeline: 'Timeline', triageL: 'Triage', respondL: 'Reply to reporter', noteL: 'Internal note', closeL: 'Close case',
    applySev: 'Apply severity', advance: 'Advance stage →', sendReply: 'Send reply', addNote: 'Add note', showOutcome: 'Show the outcome to the reporter',
    signStageL: 'Stage signature', signStage: 'Sign this stage', stageSigned: 'Stage signed and chained to the case trail · verification link copied',
    replyPh: 'Message visible to the reporter (via protocol)…', notePh: 'Confidential note (never sent to the reporter)…', closePh: 'Resolution / case outcome…',
    ev: { note: 'internal note', opening: 'opened', closing: 'closure', stage: 'stage', fromReporter: 'from reporter', toReporter: 'to reporter' },
    notFoundProtocol: 'Case not found in this module.',
    fail: 'Action failed.', failOpen: 'Failed to open the case.', loading: 'Loading…', downloadPdf: 'Download PDF', createChannel: 'Create a whistleblowing channel',
    inv: {
      title: 'Investigation', release: 'Release flow',
      releaseHint: 'Creates the review cards and starts the investigation following the channel flow.',
      anyOf: 'Anyone from', closer: 'Closing', give: 'Give my review', decision: 'Decision',
      rating: 'Rating', urgency: 'Urgency', pareceerPh: 'Write your review…', submit: 'Send review', sent: 'Review sent.',
      signed: 'Signed ✓', verifyLink: 'Verify', submitSign: 'Sign & send',
      sigRequired: 'This stage requires your digital signature. On submit we open the signature (rubric + location) and the case moves on.',
      flowManaged: 'Advancing and closing are driven by the review flow above.',
      needRubric: 'Draw your signature to sign.', signAndSend: 'Sign & send review',
      status: { pending: 'Waiting', active: 'Your turn', submitted: 'Done', skipped: 'Skipped' },
      dec: { agree: 'Agree', more_info: 'More investigation', dismiss: 'Dismiss' },
      urg: { low: 'Low', medium: 'Medium', high: 'High' },
    },
  },
  nr1: {
    title: 'NR-1 Psychosocial',
    subtitle: 'Aggregated results by theme axis.',
    locked: 'The NR-1 module is not in your plan.',
    axis: 'Axis',
    average: 'Average',
    responses: 'Responses',
    cycle: 'Cycle', egCycle: '2026-Q2',
  },
  locked: {
    title: 'Available on higher plans',
    body: 'This module is not in your current plan.',
  },
  settings: {
    title: 'Settings',
    subtitle: 'Preferences, account and your data (LGPD).',
    appearance: 'Appearance',
    theme: 'Theme',
    light: 'Light',
    dark: 'Dark',
    system: 'System',
    fontSize: 'Font size',
    sizeS: 'Small',
    sizeM: 'Medium',
    sizeL: 'Large',
    sizeXL: 'Largest',
    language: 'Language',
    langAuto: 'Automatic',
    langHint: 'We apply this language whenever you open the site in this browser.',
    account: 'Account',
    name: 'Name',
    save: 'Save',
    changePassword: 'Change password',
    currentPassword: 'Current password',
    newPassword: 'New password',
    privacy: 'Privacy',
    privacyIntro: 'Download, adjust or delete your data anytime — you are in control.',
    exportData: 'Your data',
    exportHint: 'Download everything we store about you.',
    aiTitle: 'AI usage', aiUnlimited: 'Unlimited AI tokens on this plan.', aiTokens: 'tokens',
    aiRemaining: 'Remaining', aiYou: 'Your usage', aiCompany: 'Company quota', aiNoPersonalLimit: 'no personal limit',
    aiTeamTitle: 'Team AI credits', aiTeamHint: 'Grant more tokens to each person as needed.',
    aiAddCredit: 'Add', aiCreditsPh: '+ tokens',
    download: 'Download',
    comms: 'Email communications',
    commsHint: 'Receive product news and updates.',
    on: 'On',
    off: 'Off',
    dangerZone: 'Delete account',
    dangerHint: 'Removes your account and personal data. This cannot be undone.',
    deleteAccount: 'Delete my account',
    deleteConfirmTitle: 'Delete your account?',
    deleteConfirmBody: 'This permanently removes your account, access and personal data. This action is irreversible.',
    deleteYes: 'Yes, delete everything',
    accountDeleted: 'Your account has been deleted.',
    legal: 'Documents',
    terms: 'Terms of Use',
    privacyPolicy: 'Privacy Policy',
    saved: 'Saved!',
  },
  onb: {
    welcome: 'Welcome to Soluvia',
    tagline: 'Digital trust for ethics and privacy.',
    personalize: "Let's make it yours — it takes 10 seconds.",
    start: 'Personalize',
    skip: 'Skip',
    back: 'Back',
    next: 'Continue',
    themeQ: 'Light or dark?',
    langQ: 'Which language?',
    fontQ: 'Text size',
    doneTitle: 'All set! ✨',
    doneBody: 'You can change all of this anytime in Settings.',
    enter: 'Enter',
  },
  modules: {
    etica: 'Ethics & Reports',
    sac: 'Consumer Service',
    privacidade: 'Privacy (LGPD)',
    incidentes: 'Incidents',
    nr1: 'NR-1 Psychosocial',
    assinatura: 'Digital Signature',
    admin: 'Administration',
  },
}

const es: AppStrings = {
  common: {
    loading: 'Cargando…',
    retry: 'Reintentar',
    cancel: 'Cancelar',
    save: 'Guardar',
    create: 'Crear',
    close: 'Cerrar',
    search: 'Buscar',
    empty: 'Nada por aquí todavía.',
    upgrade: 'Mejorar plan',
    comingSoon: 'Próximamente',
    logout: 'Salir',
    copy: 'Copiar',
    copied: '¡Copiado!',
    of: 'de',
  },
  topbar: { theme: 'Tema', language: 'Idioma' },
  states: {
    sessionExpired: 'Tu sesión expiró',
    sessionExpiredBody: 'Inicia sesión de nuevo para acceder al panel.',
    login: 'Iniciar sesión',
    noCompany: 'Tu cuenta aún no pertenece a ninguna empresa activa.',
    subscribe: 'Elegir un plan',
    backToSite: 'Volver al sitio',
    chooseCompany: 'Elige la empresa',
    loadingPanel: 'Preparando tu panel…',
  },
  nav: {
    main: 'General',
    ops: 'Operación',
    modules: 'Módulos',
    config: 'Canales y formularios',
    admin: 'Administración',
    overview: 'Resumen',
    cases: 'Canal de Denuncias',
    sac: 'SAC',
    nr1: 'NR-1',
    signature: 'Firma Digital',
    people: 'Personas',
    roles: 'Roles',
    channels: 'Canales',
    formbuilder: 'Formulario',
    flow: 'Flujo',
    billing: 'Plan',
    audit: 'Auditoría',
    settings: 'Configuración',
  },
  flowSac: {
    subtitle: 'Diseña la cadena que sigue una demanda de consumidor tras abrirse — las etapas de la atención, quién responde y el plazo.',
    stages: 'Etapas de la atención (configurables)',
    emptyStagesBody: 'Agrega las subetapas de la atención — cada una con responsable, observadores y plazo.',
    railInvestigation: 'Averiguación',
    egName: 'Atención',
    stageNamePh: 'Ej.: Análisis del pedido',
  },
  flow: {
    title: 'Constructor de Flujo',
    subtitle: 'Diseña la cadena que sigue un reporte tras enviarse — las etapas de la investigación, quién responde y el plazo.',
    save: 'Guardar flujo', saved: 'Flujo guardado.', saveFail: 'Error al guardar el flujo.',
    channel: 'Canal', flowName: 'Nombre del flujo', egName: 'Investigación',
    rail: 'La cadena completa', railReceived: 'Recibido', railTriage: 'Triaje', railInvestigation: 'Investigación', railResponded: 'Respuesta', railClosed: 'Cerrado',
    stages: 'Etapas de la investigación (configurables)',
    emptyStages: 'Aún no hay etapas', emptyStagesBody: 'Agrega las subetapas de la investigación — cada una con responsable, observadores y plazo.',
    addStage: 'Agregar etapa', untitled: 'Etapa sin nombre',
    noChannel: 'Sin canal para configurar', noChannelBody: 'Crea un canal en Canales para armar su flujo.',
    operator: 'Responsable (opera)', noRole: 'Sin responsable', sla: 'Plazo (días)', watchers: 'Observadores (siguen)',
    operatorPerson: 'Persona (opcional)', anyOfRole: 'Cualquiera del rol',
    doesWhat: 'Qué hace esta persona', cfgDecision: 'Decisión', cfgRating: 'Nota', cfgUrgency: 'Urgencia',
    mode: 'Modo del flujo', sequential: 'Secuencial', parallel: 'Paralelo',
    sequentialHint: 'Una etapa por vez — cada dictamen libera la siguiente.',
    parallelHint: 'Todos lo reciben a la vez; cada uno da su dictamen.',
    closerRole: 'Cierre (rol)', closerPerson: 'Cierre (persona)',
    requireSig: 'Exigir firma digital en esta etapa', requireSigHint: 'El evaluador solo pasa a la siguiente etapa tras firmar digitalmente su dictamen.',
    closerRequireSig: 'Exigir la firma digital del cierre',
    searchPerson: 'Buscar por nombre o correo…', noPerson: 'Nadie encontrado.',
    stageNamePh: 'Ej.: Averiguación preliminar', conditional: 'Etapa condicional', condPrefix: 'Solo se ejecuta si la gravedad es',
    sev: { low: 'Baja', medium: 'Media', high: 'Alta', critical: 'Crítica' },
  },
  login: {
    title: 'Iniciar sesión',
    kicker: 'Acceder a Soluvia',
    email: 'Correo',
    password: 'Contraseña',
    enter: 'Entrar',
    entering: 'Entrando…',
    wrong: 'Correo o contraseña inválidos.',
    noAccount: '¿Aún no tienes cuenta?',
    subscribe: 'Elegir un plan',
    chooseCompany: '¿En qué empresa quieres entrar?',
    chooseSub: 'Tu identidad es única; el acceso cambia según la empresa.',
  },
  overview: {
    title: 'Panel de',
    modulesTitle: 'Tus módulos',
    mod: {
      etica: { name: 'Canal de Denuncias', desc: 'Recibe y gestiona reportes con confidencialidad y trazabilidad.' },
      sac: { name: 'SAC · Atención al Consumidor', desc: 'Demandas de consumidores con plazo de 7 días corridos.' },
      assinatura: { name: 'Firma Digital', desc: 'Firma documentos y etapas con validez y evidencia.' },
      nr1: { name: 'NR-1 · Riesgo psicosocial', desc: 'Encuestas e indicadores de salud mental en el trabajo.' },
      privacidade: { name: 'Privacidad (LGPD)', desc: 'Solicitudes de titulares y cumplimiento.' },
      incidentes: { name: 'Incidentes', desc: 'Registro y gestión de incidentes.' },
    },
    welcome: 'Has iniciado sesión como Admin. Este es tu entorno.',
    welcomeMember: 'Bienvenido de nuevo. Este es tu entorno.',
    plan: 'Plan',
    users: 'Usuarios',
    seatsFree: 'plaza(s) libre(s)',
    modules: 'Módulos activos',
    openCases: 'Casos abiertos',
    recent: 'Actividad reciente',
    quick: 'Acciones rápidas',
    quickInvite: 'Invitar persona',
    quickChannel: 'Crear canal',
    quickRoles: 'Gestionar roles',
    yourRoles: 'Tus roles',
  },
  people: {
    title: 'Personas',
    subtitle: 'Invita al equipo y asigna roles y alcance.',
    invite: 'Invitar persona',
    inviteTitle: 'Invitar persona',
    emailPh: 'persona@empresa.com',
    namePh: 'Nombre (opcional)',
    role: 'Rol',
    noRole: 'Sin rol',
    send: 'Enviar invitación',
    sending: 'Enviando…',
    seats: 'plazas usadas',
    remove: 'Quitar',
    active: 'activo',
    invited: 'invitado',
    suspended: 'suspendido',
    copyInvite: 'Copiar invitación',
    resend: 'Reenviar', resending: 'Enviando…',
    oneEmailRule: 'Un correo vale por una cuenta, en una sola empresa. Si la persona ya está en la plataforma, usa otra dirección.',
    resendHint: 'Envía la invitación de nuevo, con un código nuevo. El enlace sigue igual.',
    resendOk: 'Invitación reenviada — un código nuevo fue al correo.',
    resendFail: 'No se pudo reenviar la invitación.',
    inviteCreated: '¡Invitación creada!',
    inviteLinkHint: 'El correo aún no está conectado: copia el enlace y envíalo manualmente. La persona define su contraseña y entra a su panel.',
    inviteAnother: 'Invitar a otra',
  },
  roles: {
    title: 'Roles',
    subtitle: 'Roles del sistema y los personalizados de tu empresa.',
    egRole: 'Operador de Ética',
    system: 'Sistema',
    custom: 'Personalizado',
    permissions: 'permisos',
    new: 'Nuevo rol',
    builderNew: 'Crear rol',
    builderEdit: 'Editar rol',
    identity: 'Identidad',
    name: 'Nombre del rol',
    color: 'Color',
    icon: 'Ícono',
    from: 'Partir de una plantilla',
    blank: 'En blanco',
    modulesH: 'Permisos por módulo',
    all: 'Todos',
    none: 'Ninguno',
    preview: 'Vista previa',
    activeCount: 'permisos activos',
    save: 'Guardar rol',
    saving: 'Guardando…',
    remove: 'Quitar',
    confirmRemove: '¿Quitar este rol? Primero hay que remover las asignaciones.',
    readonly: 'Rol del sistema — solo lectura.',
    edit: 'Editar',
  },
  channels: {
    title: 'Canales',
    subtitle: 'Canales por módulo y el enlace exclusivo del Colaborador.',
    egName: 'Canal de Ética', egSlug: 'canal-de-etica',
    create: 'Crear canal',
    name: 'Nombre del canal',
    slug: 'Identificador (slug)',
    module: 'Módulo',
    link: 'Enlace público',
    active: 'activo',
    inactive: 'inactivo',
    empty: 'Aún no hay canales. Crea el primero.',
  },
  billing: {
    title: 'Plan y cobro',
    subtitle: 'Tu plan actual, uso y módulos contratados.',
    current: 'Plan actual',
    seats: 'Usuarios',
    modules: 'Módulos',
    card: 'Tarjeta',
    cycle: 'Ciclo',
    monthly: 'mensual',
    yearly: 'anual',
    upgrade: 'Cambiar de plan',
    status: 'Estado',
    active: 'Activa',
    canceledTag: 'Cancelada',
    accessUntil: 'Acceso hasta',
    renews: 'Se renueva el',
    currentPlan: 'Plan actual',
    doUpgrade: 'Mejorar plan',
    doDowngrade: 'Bajar plan',
    switchCycle: 'Cambiar ciclo',
    cancelSub: 'Cancelar suscripción',
    reactivate: 'Reactivar suscripción',
    cancelTitle: '¿Cancelar suscripción?',
    cancelBody: 'Tu suscripción sigue activa hasta el final del período ya pagado. Después, el acceso se suspende y no hay un nuevo cargo. Puedes reactivarla cuando quieras.',
    canceledBanner: 'Suscripción cancelada — mantienes el acceso hasta el final del período.',
    keep: 'Mantener suscripción',
    changeTitle: 'Revisar cambio',
    fromTo: 'Cambio de plan',
    payNow: 'A pagar ahora (prorrateado)',
    creditNext: 'Crédito en la próxima factura',
    daysLeft: 'días restantes en este ciclo',
    noCharge: 'Sin cargo adicional ahora.',
    confirmChange: 'Confirmar cambio',
    seatWarn: 'Reduce el número de usuarios activos antes de cambiar a este plan.',
    dangerZone: 'Gestionar suscripción',
    cardOnFile: 'Protegido por Stripe',
    errCalc: 'Error al calcular el cambio.',
    errChange: 'Error al cambiar de plan.',
    errCancel: 'Error al cancelar.',
    errReactivate: 'Error al reactivar.',
  },
  fb: {
    title: 'Constructor de Formulario',
    subtitle: 'Arma el formulario de denuncia del canal — como un Google Forms.',
    noChannel: 'Aún no hay canal de ética',
    noChannelBody: 'Crea un canal en "Canales" para armar el formulario de denuncias.',
    save: 'Guardar', publish: 'Publicar', published: '¡Formulario publicado!', saved: 'Borrador guardado',
    errSave: 'Error al guardar.', errTranslate: 'Error al traducir.',
    previewYes: 'Sí', previewNo: 'No', optionEg: 'Opción',
    myForms: 'Mis formularios', untitled: 'Sin título', fieldsWord: 'campos',
    kindEtica: 'Canal de Denuncias', kindSac: 'SAC',
    identity: 'Identidad del formulario', formTitle: 'Título del formulario',
    formIntro: 'Texto de introducción (opcional)', identification: 'Identificación del denunciante',
    id: { optional: 'Opcional', required: 'Obligatoria', forbidden: 'Anónimo' },
    question: 'Pregunta', remove: 'Quitar', help: 'Texto de ayuda (opcional)',
    optionsPh: 'Una opción por línea', required: 'Obligatorio', sensitive: 'Sensible (privacidad)',
    addField: 'Agregar pregunta', preview: 'Vista previa', publishedTag: 'Publicado',
    draft: 'Borrador', answerPh: 'Respuesta del denunciante', choosePh: 'Selecciona',
    publicLink: 'Enlace público del canal', publishHint: 'Publica el formulario para activar el enlace.',
    types: { short_text: 'Texto corto', long_text: 'Texto largo', single_choice: 'Elección única', multi_choice: 'Opción múltiple', dropdown: 'Lista desplegable', date: 'Fecha', yes_no: 'Sí / No', rating: 'Puntuación', section: 'Título de sección', info: 'Texto informativo' },
    mode: { manual: 'Manual', ai: 'Crear con IA' },
    langBuild: 'Idioma del formulario', translate: 'Traducir a todos los idiomas', translating: 'Traduciendo…', translated: 'Formulario traducido (PT · EN · ES).', langsReady: 'Listo en:',
    previewOffTitle: 'Idioma aún no traducido', previewOffBody: 'Este formulario aún no tiene versión en este idioma. Traduce para previsualizar.', previewOffCta: 'Traducir ahora',
    ai: { title: 'Asistente de formulario', intro: '¡Hola! Cuéntame qué canal quieres crear y armo el formulario por ti — siguiendo la NR-1 y la Ley 14.457/2022, con preguntas amables y cuidadosas. Pide cambios cuando quieras. 😊', placeholder: 'Ej.: canal de acoso para una fábrica, anónimo, con campo de sector…', send: 'Enviar', thinking: 'Creando…', apply: 'Usar este formulario', applied: 'Formulario aplicado — revisa y publica.', you: 'Tú', assistant: 'Asistente', agentEtica: 'Especialista en ouvidoría', agentSac: 'Especialista en SAC', newChat: 'Nueva conversación', deleteChat: 'Eliminar conversación', empty: 'Empieza describiendo el canal que necesitas.', starters: ['Acoso moral y sexual', 'Fraude y corrupción', 'Ética y conducta general'], introSac: '¡Hola! Cuéntame cómo es la atención de tu empresa y armo el formulario del SAC — siguiendo el Código de Defensa del Consumidor y el Decreto 11.034/2022. Identificación obligatoria y respuesta en hasta 7 días corridos ya vienen por defecto. 😊', startersSac: ['Reclamo de producto', 'Cancelación de servicio', 'Dudas e información'], waiting: ['Entendiendo lo que necesitas…', 'Pensando las mejores preguntas…', 'Aplicando la NR-1 y la Ley 14.457…', 'Cuidando un tono cálido…', 'Organizando los campos…', 'Casi listo, finalizando…'] },
  },
  sig: {
    title: 'Firma Digital',
    subtitle: 'Sube un documento, coloca los campos y firma con validez jurídica.',
    docs: 'Documentos',
    upload: 'Subir documento',
    uploading: 'Subiendo…',
    dropHint: 'Arrastra un PDF o DOCX aquí, o haz clic para elegir',
    dropTypes: 'Solo .pdf y .docx · hasta 20 MB',
    invalidType: 'Formato no admitido. Sube un archivo .pdf o .docx.',
    tooBig: 'Archivo demasiado grande (máx. 20 MB).',
    uploadFail: 'No se pudo subir el documento.',
    emptyDocs: 'Aún no hay documentos',
    emptyDocsBody: 'Sube tu primer documento para empezar a firmar.',
    created: 'Subido el',
    status: { uploaded: 'En espera', partial: 'Parcial', signed: 'Firmado' },
    open: 'Abrir',
    back: 'Volver a los documentos',
    prepare: 'Preparar',
    sign: 'Firmar',
    evidence: 'Comprobante',
    // Viewer
    page: 'Página',
    of: 'de',
    zoomIn: 'Acercar',
    zoomOut: 'Alejar',
    addFieldHint: 'Haz clic y arrastra sobre el documento para crear un campo de firma.',
    fieldsCount: 'campo(s) de firma',
    saveFields: 'Guardar campos',
    savingFields: 'Guardando…',
    fieldsSaved: 'Campos guardados.',
    fieldsFail: 'No se pudieron guardar los campos.',
    clearFields: 'Limpiar campos',
    signHere: 'Firmar aquí',
    removeField: 'Quitar campo',
    resizeField: 'Redimensionar campo',
    fitPage: 'Ajustar',
    fitPageHint: 'Encuadrar la página entera',
    addFieldMode: 'Añadir campo',
    addFieldHintTouch: 'Activa "Añadir campo" y toca donde debe ir la firma. Con el modo apagado, desplazas el documento con normalidad.',
    moveFieldHint: 'Arrastra un campo para moverlo; tira de la esquina para redimensionar.',
    fieldsSavedShort: 'Guardado',
    noFieldsWarn: 'Ningún campo colocado. La firma se estampará al pie de la última página.',
    unsavedFields: 'Los campos aún se están guardando. Vuelve a "Preparar", confirma que dice "Guardado" e inténtalo de nuevo — si no, la firma irá al pie de la última página.',
    loadingPdf: 'Cargando documento…',
    pdfFail: 'No se pudo renderizar este PDF.',
    docxTitle: 'Documento Word (.docx)',
    docxBody: 'La posición de los campos es una función del PDF. Los documentos .docx se firman con un bloque de firma añadido al final del archivo.',
    // Acto de firmar
    signTitle: 'Firmar documento',
    signKicker: 'Firma avanzada',
    rubric: 'Tu firma',
    rubricHint: 'Dibuja tu firma en el recuadro de abajo (visual).',
    rubricDraw: 'Dibujar',
    rubricType: 'Generar del nombre',
    rubricRequired: 'Añade tu rúbrica antes de firmar — dibújala o espera a que aparezca la generada.',
    typedName: 'Nombre que aparecerá en la firma',
    typedPlaceholder: 'Tu nombre',
    typedStyle: 'Estilo de letra',
    typedStyles: { classica: 'Clásica', fluida: 'Fluida', caneta: 'Pluma', marcador: 'Marcador' },
    typedLoading: 'Cargando estilos de letra…',
    typedHint: 'La firma se genera a partir del nombre escrito. El valor jurídico viene de la firma electrónica (clave, fecha/hora y traza de auditoría), no del dibujo.',
    clear: 'Limpiar',
    cpf: 'CPF (opcional)',
    cpfHint: 'Refuerza la identidad del firmante. Solo lo guardamos enmascarado.',
    remember: 'Guardar mi rúbrica en este dispositivo para la próxima vez (documento y ubicación nunca se guardan)',
    typeLabel: 'Tipo de firma', typeRubric: 'Rúbrica', typeSeal: 'Firma digital',
    sealHint: 'Aplica un sello oficial de firma electrónica con tu nombre, CPF, fecha/hora y código de verificación — sin necesidad de dibujar.',
    geoTitle: 'Ubicación',
    geoHint: 'Adjuntar tu ubicación refuerza la prueba. Te pediremos permiso.',
    consentTitle: '¿Compartir tu ubicación?',
    consentBody: 'Con tu consentimiento, capturamos las coordenadas de tu dispositivo solo en este momento para reforzar la evidencia de la firma. Puedes firmar sin compartir.',
    consentAllow: 'Permitir y capturar',
    consentDeny: 'Firmar sin ubicación',
    geoOn: 'Ubicación capturada',
    geoOff: 'Sin ubicación',
    geoDenied: 'Permiso denegado — firmaremos sin ubicación.',
    geoUnavailable: 'Ubicación no disponible en este dispositivo.',
    geoGetting: 'Obteniendo ubicación…',
    confirmSign: 'Firmar ahora',
    signing: 'Firmando…',
    signFail: 'No se pudo firmar el documento.',
    signed: '¡Documento firmado!',
    // Comprobante
    evTitle: 'Comprobante de firma',
    evSubtitle: 'Rastro de evidencias criptográficas de este documento.',
    evFile: 'Archivo',
    evHash: 'Hash original (SHA-256)',
    evStatus: 'Estado',
    evChain: 'Cadena de evidencias',
    chainOk: 'Íntegra',
    chainBroken: 'Comprometida',
    signers: 'Firmantes',
    noSigners: 'Aún sin firmas.',
    signerName: 'Firmante',
    algo: 'Algoritmo',
    level: 'Nivel',
    signedAt: 'Firmado el',
    geo: 'Ubicación',
    notConsented: 'no consentida',
    ip: 'IP',
    userAgent: 'Dispositivo',
    cpfMasked: 'CPF',
    cpfStatus: 'Situación del CPF',
    evHashLabel: 'Hash de la evidencia',
    prevHash: 'Hash anterior',
    verifyToken: 'Token de verificación',
    downloadSigned: 'Descargar archivo firmado',
    downloading: 'Descargando…',
    downloadFail: 'No se pudo descargar el archivo.',
    copyVerify: 'Copiar enlace de verificación',
    verifyLink: 'Enlace de verificación',
    evLoadFail: 'No se pudo cargar el comprobante.',
  },
  audit: {
    title: 'Auditoría',
    subtitle: 'Rastro inmutable de todo lo que ocurre en la empresa — quién hizo qué, y cuándo.',
    empty: 'Sin registros todavía.', noMatch: 'Ningún evento con esos filtros.',
    filters: 'Filtros', from: 'Desde', to: 'Hasta', action: 'Acción', person: 'Persona',
    all: 'Todas las acciones', allPeople: 'Todas las personas', search: 'Buscar…', clear: 'Limpiar filtros',
    events: 'eventos', system: 'Sistema', today: 'Hoy', yesterday: 'Ayer',
    export: 'Exportar PDF', exporting: 'Generando…', exportOk: 'PDF generado.', exportFail: 'Error al generar el PDF.',
    integrityOk: 'Registro íntegro', integrityBroken: 'Integridad comprometida',
    integrityHint: 'Cada evento encadena el anterior por hash (SHA-256). La cadena se recalculó y está intacta — ningún registro fue alterado o eliminado.',
    integrityBrokenHint: 'La cadena de hash no coincide: un registro fue alterado o eliminado. Contacta con soporte.',
    exportTitle: 'Rastro de auditoría', colWhen: 'Cuándo', colWho: 'Quién', colWhat: 'Qué ocurrió', colDetail: 'Detalle',
    cat: { case: 'Casos', signature: 'Firma', flow: 'Flujo', channel: 'Canales y formularios', role: 'Roles y personas', billing: 'Plan', account: 'Cuenta y privacidad', tenant: 'Empresa', other: 'Otros' },
    res: { sig_document: 'documento', channel: 'canal', case: 'caso', flow: 'flujo', role: 'rol', user: 'usuario', tenant: 'empresa', data_request: 'solicitud de privacidad', membership: 'miembro' },
    act: {
      'signature.signed': 'firmó un documento', 'flow.saved': 'guardó el flujo de un canal',
      'case.created': 'abrió un caso', 'case.advanced': 'avanzó la etapa de un caso', 'case.closed': 'cerró un caso',
      'case.event.message': 'respondió al denunciante', 'case.event.note': 'agregó una nota interna',
      'case.event.status_change': 'cambió el estado de un caso', 'case.event.stage_change': 'cambió la etapa de un caso',
      'case.event.created': 'registró un evento del caso', 'case.event.closed': 'cerró un caso',
      'channel.created': 'creó un canal', 'channel.updated': 'actualizó un canal',
      'channel.form_saved': 'guardó el formulario de un canal', 'channel.form_translated': 'tradujo el formulario de un canal',
      'channel.form_published': 'publicó el formulario de un canal',
      'role.created': 'creó un rol', 'role.updated': 'editó un rol', 'role.deleted': 'eliminó un rol',
      'membership.invited': 'invitó a una persona', 'membership.accepted': 'aceptó una invitación',
      'membership.status_changed': 'cambió el estado de un miembro', 'membership.removed': 'eliminó a un miembro',
      'membership.role_assigned': 'asignó un rol a un miembro', 'membership.role_removed': 'quitó un rol a un miembro',
      'billing.subscribed': 'contrató un plan', 'billing.plan_changed': 'cambió de plan',
      'billing.canceled': 'canceló la suscripción', 'billing.reactivated': 'reactivó la suscripción',
      'billing.webhook': 'recibió un evento de pago',
      'account.deleted': 'eliminó su cuenta', 'account.profile_updated': 'actualizó su perfil',
      'account.password_changed': 'cambió su contraseña', 'lgpd.data_exported': 'exportó sus datos (privacidad)',
      'lgpd.request': 'hizo una solicitud de privacidad', 'tenant.self_signup': 'registró la empresa',
      'tenant.provisioned': 'aprovisionó la empresa', 'tenant.profile_updated': 'actualizó los datos de la empresa',
    },
  },
  sac: {
    title: 'SAC — Atención al Consumidor',
    subtitle: 'Demandas de consumidores, con plazo de respuesta de 7 días corridos (Decreto 11.034/2022).',
    createChannel: 'Crear un canal de SAC',
    due: { late: 'Atrasado', today: 'Vence hoy', inDays: 'Faltan {n} d' },
    empty: 'Ninguna demanda en tu alcance todavía.',
    noActive: 'Ninguna demanda abierta.', noFinished: 'Ninguna demanda finalizada todavía.',
    active: 'Abiertas', finished: 'Finalizadas',
    searchPh: 'Buscar por título o protocolo…',
    relato: 'Demanda', closeL: 'Cerrar demanda',
    respondL: 'Responder al consumidor', showOutcome: 'Mostrar el desenlace al consumidor',
    rsigTitle: 'Firma del consumidor',
    replyPh: 'Mensaje visible al consumidor (por el protocolo)…',
    notePh: 'Nota interna (nunca va al consumidor)…',
    closePh: 'Desenlace de la demanda…',
    failOpen: 'No fue posible abrir la demanda.',
    notFoundProtocol: 'Solicitud no encontrada en este módulo.',
    ev: { note: 'nota interna', opening: 'apertura', closing: 'cierre', stage: 'etapa',
          fromReporter: 'del consumidor', toReporter: 'al consumidor' },
  },
  cases: {
    title: 'Casos',
    subtitle: 'Reportes dentro de tu alcance de acceso.',
    protocol: 'Protocolo',
    status: 'Estado',
    severity: 'Gravedad',
    opened: 'Abierto el',
    empty: 'Aún no hay casos en tu alcance.',
    active: 'Activas', finished: 'Cerradas',
    noActive: 'No hay denuncias activas por ahora.', noFinished: 'Ninguna cerrada aún.',
    searchPh: 'Buscar por título o protocolo…', noMatch: 'Nada coincide con tu búsqueda.',
    sev: { low: 'Baja', medium: 'Media', high: 'Alta', critical: 'Crítica' },
    stat: { received: 'Recibido', triage: 'Triaje', investigation: 'Investigación', responded: 'Respondido', closed: 'Cerrado' },
    anon: 'Anónimo', identified: 'Identificado',
    rsigTitle: 'Firma del denunciante', rsigSignedAt: 'Firmado el', rsigCpf: 'CPF', rsigGeo: 'Ubicación', rsigNoGeo: 'no informada',
    relato: 'Denuncia', timeline: 'Cronología', triageL: 'Triaje', respondL: 'Responder al denunciante', noteL: 'Nota interna', closeL: 'Cerrar caso',
    applySev: 'Aplicar gravedad', advance: 'Avanzar etapa →', sendReply: 'Enviar respuesta', addNote: 'Agregar nota', showOutcome: 'Mostrar el desenlace al denunciante',
    signStageL: 'Firma de la etapa', signStage: 'Firmar esta etapa', stageSigned: 'Etapa firmada y encadenada al historial del caso · enlace de verificación copiado',
    replyPh: 'Mensaje visible al denunciante (por el protocolo)…', notePh: 'Nota confidencial (nunca va al denunciante)…', closePh: 'Dictamen / desenlace del caso…',
    ev: { note: 'nota interna', opening: 'apertura', closing: 'cierre', stage: 'etapa', fromReporter: 'del denunciante', toReporter: 'al denunciante' },
    notFoundProtocol: 'Caso no encontrado en este módulo.',
    fail: 'Falló la acción.', failOpen: 'No se pudo abrir el caso.', loading: 'Cargando…', downloadPdf: 'Descargar PDF', createChannel: 'Crear un canal de denuncias',
    inv: {
      title: 'Investigación', release: 'Liberar flujo',
      releaseHint: 'Genera los dictámenes e inicia la investigación siguiendo el flujo del canal.',
      anyOf: 'Cualquiera de', closer: 'Cierre', give: 'Dar mi dictamen', decision: 'Decisión',
      rating: 'Nota', urgency: 'Urgencia', pareceerPh: 'Escribe tu dictamen…', submit: 'Enviar dictamen', sent: 'Dictamen enviado.',
      signed: 'Firmado ✓', verifyLink: 'Verificar', submitSign: 'Firmar y enviar',
      sigRequired: 'Esta etapa exige tu firma digital. Al enviar abrimos la firma (rúbrica + ubicación) y el caso avanza.',
      flowManaged: 'El avance y el cierre los controla el flujo de dictámenes de arriba.',
      needRubric: 'Dibuja tu rúbrica para firmar.', signAndSend: 'Firmar y enviar dictamen',
      status: { pending: 'En espera', active: 'Tu turno', submitted: 'Hecho', skipped: 'Omitido' },
      dec: { agree: 'De acuerdo', more_info: 'Más investigación', dismiss: 'Archivar' },
      urg: { low: 'Baja', medium: 'Media', high: 'Alta' },
    },
  },
  nr1: {
    title: 'NR-1 Psicosocial',
    subtitle: 'Resultados agregados por eje temático.',
    locked: 'El módulo NR-1 no está en tu plan.',
    axis: 'Eje',
    average: 'Media',
    responses: 'Respuestas',
    cycle: 'Ciclo', egCycle: '2026-T2',
  },
  locked: {
    title: 'Disponible en planes superiores',
    body: 'Este módulo no está en tu plan actual.',
  },
  settings: {
    title: 'Configuración',
    subtitle: 'Preferencias, cuenta y tus datos (LGPD).',
    appearance: 'Apariencia',
    theme: 'Tema',
    light: 'Claro',
    dark: 'Oscuro',
    system: 'Sistema',
    fontSize: 'Tamaño de fuente',
    sizeS: 'Pequeña',
    sizeM: 'Media',
    sizeL: 'Grande',
    sizeXL: 'Máxima',
    language: 'Idioma',
    langAuto: 'Automático',
    langHint: 'Aplicamos este idioma siempre que abras el sitio en este navegador.',
    account: 'Cuenta',
    name: 'Nombre',
    save: 'Guardar',
    changePassword: 'Cambiar contraseña',
    currentPassword: 'Contraseña actual',
    newPassword: 'Nueva contraseña',
    privacy: 'Privacidad',
    privacyIntro: 'Descarga, ajusta o elimina tus datos cuando quieras — tú tienes el control.',
    exportData: 'Tus datos',
    exportHint: 'Descarga todo lo que guardamos sobre ti.',
    aiTitle: 'Uso de IA', aiUnlimited: 'Tokens de IA ilimitados en este plan.', aiTokens: 'tokens',
    aiRemaining: 'Restantes', aiYou: 'Tu consumo', aiCompany: 'Cuota de la empresa', aiNoPersonalLimit: 'sin límite personal',
    aiTeamTitle: 'Créditos de IA del equipo', aiTeamHint: 'Libera más tokens a cada persona según la necesidad.',
    aiAddCredit: 'Agregar', aiCreditsPh: '+ tokens',
    download: 'Descargar',
    comms: 'Comunicaciones por correo',
    commsHint: 'Recibir novedades y avisos del producto.',
    on: 'Activado',
    off: 'Desactivado',
    dangerZone: 'Eliminar cuenta',
    dangerHint: 'Elimina tu cuenta y tus datos personales. No se puede deshacer.',
    deleteAccount: 'Eliminar mi cuenta',
    deleteConfirmTitle: '¿Eliminar tu cuenta?',
    deleteConfirmBody: 'Esto elimina permanentemente tu cuenta, accesos y datos personales. Esta acción es irreversible.',
    deleteYes: 'Sí, eliminar todo',
    accountDeleted: 'Tu cuenta ha sido eliminada.',
    legal: 'Documentos',
    terms: 'Términos de Uso',
    privacyPolicy: 'Política de Privacidad',
    saved: '¡Guardado!',
  },
  onb: {
    welcome: 'Bienvenido a Soluvia',
    tagline: 'Confianza digital para ética y privacidad.',
    personalize: 'Hagámoslo a tu manera — toma 10 segundos.',
    start: 'Personalizar',
    skip: 'Omitir',
    back: 'Atrás',
    next: 'Continuar',
    themeQ: '¿Claro u oscuro?',
    langQ: '¿Qué idioma?',
    fontQ: 'Tamaño del texto',
    doneTitle: '¡Todo listo! ✨',
    doneBody: 'Puedes cambiar todo esto cuando quieras en Configuración.',
    enter: 'Entrar',
  },
  modules: {
    etica: 'Ética y Denuncias',
    sac: 'SAC · Atención al Consumidor',
    privacidade: 'Privacidad (LGPD)',
    incidentes: 'Incidentes',
    nr1: 'NR-1 Psicosocial',
    assinatura: 'Firma Digital',
    admin: 'Administración',
  },
}

const STRINGS: Record<Lang, AppStrings> = { pt, en, es }

/** Hook: devolve as strings do idioma atual (mesma fonte do site). */
export function useT(): AppStrings {
  const { lang } = useTranslation()
  return STRINGS[lang] ?? pt
}

export type { AppStrings }
